import * as fs from "fs";
import * as path from "path";
import {
  getTrend,
  getContractHistory,
} from "../storage/stateStorage";

// ── Types ─────────────────────────────────────────────────────
type BlockReport = {
  blockNumber: number;
  totalTx: number;
  failedTx: number;
  failureRate: number;
  topFailingContracts: Record<string, number>;
};

type WeeklySnapshot = {
  blockNumber: number;
  totalTx: number;
  failedTx: number;
  failureRate: number;
  topFailingContracts: Record<string, number>;
  timestamp: number;
};

// ── Weekly accumulator ────────────────────────────────────────
const WEEK_MS = 7 * 24 * 60 * 60 * 1000;
const REPORTS_DIR = path.join(process.cwd(), "reports");
const WEEKLY_STORE = path.join(REPORTS_DIR, "weekly-store.json");

let weeklySnapshots: WeeklySnapshot[] = [];
let weeklyStartTime: number = Date.now();

// Load existing snapshots from disk on startup
function loadWeeklyStore() {
  try {
    if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });
    if (fs.existsSync(WEEKLY_STORE)) {
      const raw = fs.readFileSync(WEEKLY_STORE, "utf-8");
      const parsed = JSON.parse(raw);
      weeklySnapshots = parsed.snapshots || [];
      weeklyStartTime = parsed.startTime || Date.now();
      console.log(`📂 Loaded ${weeklySnapshots.length} snapshots from weekly store`);
    }
  } catch {
    weeklySnapshots = [];
    weeklyStartTime = Date.now();
  }
}

// Persist snapshots to disk
function saveWeeklyStore() {
  try {
    if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });
    fs.writeFileSync(WEEKLY_STORE, JSON.stringify({
      startTime: weeklyStartTime,
      snapshots: weeklySnapshots,
    }, null, 2));
  } catch (err) {
    console.error("Failed to save weekly store:", err);
  }
}

// ── Weekly report generator ───────────────────────────────────
function generateWeeklyReport() {
  if (weeklySnapshots.length === 0) {
    console.log("⚠️  No data collected for weekly report.");
    return;
  }

  const now = new Date();
  const startDate = new Date(weeklyStartTime);

  const totalBlocks    = weeklySnapshots.length;
  const totalTx        = weeklySnapshots.reduce((s, b) => s + b.totalTx, 0);
  const totalFailed    = weeklySnapshots.reduce((s, b) => s + b.failedTx, 0);
  const avgFailureRate = weeklySnapshots.reduce((s, b) => s + b.failureRate, 0) / totalBlocks;
  const maxFailureRate = Math.max(...weeklySnapshots.map(b => b.failureRate));
  const alertBlocks    = weeklySnapshots.filter(b => b.failureRate >= 0.10).length;
  const criticalBlocks = weeklySnapshots.filter(b => b.failureRate >= 0.15).length;

  // Aggregate contract failures across the week
  const contractTotals: Record<string, number> = {};
  for (const snap of weeklySnapshots) {
    for (const [addr, count] of Object.entries(snap.topFailingContracts)) {
      contractTotals[addr] = (contractTotals[addr] || 0) + count;
    }
  }
  const topContracts = Object.entries(contractTotals)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  // Most volatile block
  const worstBlock = weeklySnapshots.reduce((prev, curr) =>
    curr.failureRate > prev.failureRate ? curr : prev
  );

  // Health score (0-100, higher = healthier)
  const healthScore = Math.max(0, Math.round(100 - (avgFailureRate * 400) - (criticalBlocks / totalBlocks * 100)));

  const divider = "=".repeat(62);
  const line    = "-".repeat(62);

  const report = [
    ``,
    divider,
    `📅  ARCSENSE WEEKLY REPORT`,
    `    ${startDate.toDateString()} → ${now.toDateString()}`,
    divider,
    ``,
    `📊  OVERVIEW`,
    line,
    `    Blocks Analyzed       : ${totalBlocks.toLocaleString()}`,
    `    Total Transactions    : ${totalTx.toLocaleString()}`,
    `    Total Failures        : ${totalFailed.toLocaleString()}`,
    `    Avg Failure Rate      : ${(avgFailureRate * 100).toFixed(2)}%`,
    `    Peak Failure Rate     : ${(maxFailureRate * 100).toFixed(2)}%`,
    ``,
    `🚨  ALERT SUMMARY`,
    line,
    `    Warning Blocks (≥10%) : ${alertBlocks}`,
    `    Critical Blocks (≥15%): ${criticalBlocks}`,
    `    Most Volatile Block   : #${worstBlock.blockNumber} — ${(worstBlock.failureRate * 100).toFixed(0)}% failure rate`,
    ``,
    `🏥  NETWORK HEALTH SCORE : ${healthScore}/100  ${healthScore >= 80 ? "✅ Healthy" : healthScore >= 50 ? "⚠️  Moderate" : "🔴 Degraded"}`,
    ``,
    `🎯  TOP FAILING CONTRACTS`,
    line,
    ...(topContracts.length === 0
      ? [`    No contract failures recorded.`]
      : topContracts.map(([addr, count], i) =>
          `    ${i + 1}. ${addr}  →  ${count} failure${count > 1 ? "s" : ""}`
        )
    ),
    ``,
    `💡  WEEKLY INSIGHT`,
    line,
    `    ${generateInsight(avgFailureRate, criticalBlocks, topContracts)}`,
    ``,
    divider,
    `    Generated by ArcSense Lite · Arc Testnet`,
    `    ${now.toISOString()}`,
    divider,
    ``,
  ].join("\n");

  // Print to terminal
  console.log(report);

  // Save to file
  try {
    if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });

    const fileName = `weekly-${startDate.toISOString().slice(0, 10)}-to-${now.toISOString().slice(0, 10)}.txt`;
    const filePath = path.join(REPORTS_DIR, fileName);
    fs.writeFileSync(filePath, report);
    console.log(`💾  Weekly report saved → reports/${fileName}`);

    // Also save JSON version for dashboard use later
    const jsonName = fileName.replace(".txt", ".json");
    fs.writeFileSync(path.join(REPORTS_DIR, jsonName), JSON.stringify({
      period: { start: weeklyStartTime, end: Date.now() },
      totalBlocks, totalTx, totalFailed,
      avgFailureRate, maxFailureRate,
      alertBlocks, criticalBlocks, healthScore,
      topContracts: Object.fromEntries(topContracts),
      worstBlock: { blockNumber: worstBlock.blockNumber, failureRate: worstBlock.failureRate },
    }, null, 2));
    console.log(`💾  JSON report saved  → reports/${jsonName}`);
  } catch (err) {
    console.error("Failed to save weekly report:", err);
  }

  // Reset for next week
  weeklySnapshots  = [];
  weeklyStartTime  = Date.now();
  saveWeeklyStore();
}

function generateInsight(
  avgRate: number,
  criticalBlocks: number,
  topContracts: [string, number][]
): string {
  if (criticalBlocks > 5) {
    return `Significant instability detected this week. ${criticalBlocks} blocks exceeded critical failure thresholds. Contract at ${topContracts[0]?.[0] || "unknown"} is the primary concern.`;
  }
  if (avgRate > 0.08) {
    return `Elevated failure rates observed across the week. Network shows moderate stress. Recommend reviewing top failing contracts before next deployment cycle.`;
  }
  if (avgRate > 0.03) {
    return `Isolated failure spikes detected but overall activity remained stable. Normal testnet behaviour with occasional contract-level issues.`;
  }
  return `Network operated within healthy parameters this week. Failure rates remained low and no sustained degradation was detected.`;
}

// ── Weekly check scheduler ────────────────────────────────────
function checkWeeklyReport() {
  const elapsed = Date.now() - weeklyStartTime;
  if (elapsed >= WEEK_MS) {
    console.log("\n📅 One week elapsed — generating weekly report...");
    generateWeeklyReport();
  }
}

// ── Init on module load ───────────────────────────────────────
loadWeeklyStore();

// Check every hour if a week has passed
setInterval(checkWeeklyReport, 60 * 60 * 1000);

// ── Main push function ────────────────────────────────────────
export function pushBlockReport(report: BlockReport) {
  const success = report.totalTx - report.failedTx;

  // Accumulate into weekly store
  weeklySnapshots.push({
    blockNumber:          report.blockNumber,
    totalTx:              report.totalTx,
    failedTx:             report.failedTx,
    failureRate:          report.failureRate,
    topFailingContracts:  report.topFailingContracts,
    timestamp:            Date.now(),
  });

  // Save to disk every 50 blocks so data survives restarts
  if (weeklySnapshots.length % 50 === 0) saveWeeklyStore();

  // ── Terminal output ───────────────────────────────────────
  console.log(`\n📦 Block ${report.blockNumber} → ${report.totalTx} tx`);

  console.log("\n📊 Report: {");
  console.log(`  total: ${report.totalTx},`);
  console.log(`  successful: ${success},`);
  console.log(`  failed: ${report.failedTx},`);
  console.log(`  failureRate: ${report.failureRate.toFixed(2)},`);

  const entries = Object.entries(report.topFailingContracts);
  console.log("  topFailingContracts: [");
  if (entries.length === 0) {
    console.log("  ],");
  } else {
    for (const [addr, count] of entries) {
      console.log(`    '${addr}', ${count}`);
    }
    console.log("  ],");
  }
  console.log("}");

  // Contract history
  const history = getContractHistory();
  console.log("\ncontractHistory: {");
  for (const [addr, count] of Object.entries(history)) {
    console.log(`  '${addr}', ${count}`);
  }
  console.log("}");

  // Trend
  const trend = getTrend();
  console.log(`\n📈 Trend: ${trend}`);

  // Insight + Severity
  let insight  = "Failure activity increasing across recent blocks";
  let severity = "LOW";

  if (report.failureRate > 0.15) {
    insight  = "Elevated failure rate detected across multiple transactions";
    severity = "HIGH";
  } else if (report.failureRate >= 0.10) {
    insight  = "Moderate failure activity detected";
    severity = "MEDIUM";
  }

  console.log(`🧠 Insight: ${insight}`);
  console.log(`🚨 Severity: ${severity}`);

  // Alert
  if (report.failureRate >= 0.10) {
    const topContract  = entries.length > 0 ? entries[0][0] : null;
    const spikePercent = (report.failureRate * 100).toFixed(0);

    console.log(`\n${"=".repeat(60)}`);
    console.log(`🚨 ALERT TRIGGERED`);
    console.log("=".repeat(60));

    if (report.failureRate >= 0.15) {
      console.log(`⛔  CRITICAL: Severe failure spike — ${spikePercent}% of transactions failed`);
    } else {
      console.log(`⚠️  WARNING: Abnormal failure spike — ${spikePercent}% of transactions failed`);
    }

    console.log(`📦 Block: #${report.blockNumber}`);
    console.log(`📉 Failed: ${report.failedTx} of ${report.totalTx} transactions`);
    if (topContract) {
      console.log(`🎯 Most active failing contract: ${topContract}`);
    }
    console.log("=".repeat(60));
  }

  // Weekly progress indicator every 100 blocks
  if (weeklySnapshots.length % 100 === 0) {
    const elapsed  = Date.now() - weeklyStartTime;
    const pct      = Math.min(100, (elapsed / WEEK_MS * 100)).toFixed(1);
    const daysLeft = Math.max(0, ((WEEK_MS - elapsed) / 86400000)).toFixed(1);
    console.log(`\n📅 Weekly report progress: ${pct}% — ${daysLeft} days remaining (${weeklySnapshots.length} blocks logged)`);
  }
}

// ── Manual trigger export (for testing) ──────────────────────
export function triggerWeeklyReport() {
  console.log("\n🛠️  Manual weekly report triggered...");
  generateWeeklyReport();
}